task:
  name: Anteiku Builder
  timeout_in: 120m
  container:
    dockerfile: Dockerfile
    cpu: 8
    memory: 32G
  environment:
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: ""
    TOKEN: ""
    CHATID: ""
    BOTTOKEN: ""
    GIT_COOKIES: ""
    TDRIVE: ""
    rom: "sakura"
    T_DEVICE: "vince"
  download_ccache_background_script:
      - bash download_ccache.sh
  upload_ccache_background_script:
      - bash upload_ccache.sh
  build_script:
      - bash build.sh
  final_upload_ccache_script:
      - bash final_upload_ccache.sh
