#!/bin/bash
cd $HOME

# Notify In telegram
telegram -M "*DERPFEST ROM Compile Status*: \`STARTED!\`.
*Started at*:- \`$(date)\`."

# Setup CCache
ccache -M 10G
ccache -z

# Run build process
build_start=$(date +"%s")
#
#
source build/envsetup.sh
lunch derp_daisy-user
mka derp -j8
#
#
build_end=$(date +"%s")
echo "$((build_end - build_start))" > ~/.build_time
