#!/bin/bash
#
cd $HOME

# Configure Git
git config --global color.ui true
git config --global user.name ZunayedDihan
git config --global user.email zunayeddihan@gmail.com

# Git Haxxx xD
echo "${git_cookies}" > ~/git_hax.sh
bash ~/git_hax.sh && rm ~/git_hax.sh

# Repo init  and sync
repo init -u git://github.com/DerpFest-11/manifest.git -b 11 --depth=1 --no-repo-verify -g default,-device,-mips,-darwin,-notdefault

# Start repo sync
repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

# Purge repo
rm -rf .repo

# Gapps
rm -rf vendor/gms
git clone --depth=1 https://gitlab.com/ZunayedDihan/vendor_gms -b 11-new vendor/gms
rm -rf device/generic/opengl-transport

# Pull Device Sources
git clone --depth=1 https://github.com/DerpFest-Devices/device_xiaomi_daisy -b 11 device/xiaomi/daisy
git clone --depth=1 https://github.com/DerpFest-Devices/vendor_xiaomi_daisy -b 11 vendor/xiaomi/daisy
git clone --depth=1 https://github.com/lupesoltec/vendor_MiuiCamera.git -b daisy vendor/MiuiCamera
git clone --depth=1 https://github.com/TheSanty/kernel_xiaomi_msm8953 -b a11/master kernel/xiaomi/msm8953
