#!/bin/bash
#
cd $HOME
build_time=$(cat ~/.build_time)
build_name=$(ls $HOME/out/target/product/daisy/ | grep -m1 -E 'daisy|.zip')
ZIP=$(find $(pwd)/out/target/product/daisy/ -maxdepth 1 -name "*daisy*.zip" | perl -e 'print sort { length($b) <=> length($a) } <>' | head -n 1)
ZIPNAME=$(basename ${ZIP})
ZIPSIZE=$(du -sh ${ZIP} |  awk '{print $1}')


# Push Compiled ROM if available
if [ -f $HOME/out/target/product/daisy/${build_name} ]; then

rclone copy $HOME/out/target/product/daisy/$build_name remote:/noob/ps/ -P
rclone copy $HOME/out/target/product/daisy/${ZIPNAME} remote:/noob/ps/ -P

telegram -M "*Project Sakura Compile Status*: \`FINISHED!\`
*Finished at*:- \`$(date)\`.
*Compile Time*: \`$((build_time / 3600)) hour(s), $((build_time % 3600 / 60)) minute(s) and $((build_time % 60)) seconds\`.
*Download Link*: [$build_name](https://noob-buildbot.zunayeddihan.workers.dev/0:/ps/$build_name)
*CCache Stats*:-
\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\`"

else

telegram -M "*Project Sakura Compile Status*: \`FAILED!\`
*Failed at*:- \`$(date)\`.
*Compile Time*: \`$((build_time / 3600)) hour(s), $((build_time % 3600 / 60)) minute(s) and $((build_time % 60)) seconds\`.
*CCache Stats*:-
\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\`"

fi
